### ISSUE TITLE
TASK: User Data Structures

### ISSUE THREAD

**Issue by jeturcotte** [sarl-hackerspace/ingredient.guru#4]
The goal here is to think through, research, propose and ultimately implement data structures to support the concept of USERS

- to be considered:
  - what is a user
  - how little can we get away with asking for to keep their privacy and security intact will still having enough data to facilitate a personalized experience on our site
  - how do they authenticate into and out of their account
  - consider that regionality may be important to users... comparing their recipes and their access to ingredients to others in their town or neighborhood
  - what behavior/history tracking is needed
  - since this is a ultimate a pro-healthy-eating service, consider structures that would support the user's voluntarily recording their basic health biometrics over time, to be scientifically compared with their eating over time

TODO:
- [x] REQ: Research what typically makes up a user
- [x] REQ: Propose data structures that will support the concept
- [x] REQ: Discuss proposal in evening meetup session
- [x] REQ: Implement data structures after proposals have been hashed out and agreed upon
- [x] REQ: Flesh out some basic APIs
  - [x] REQ: APIs for creating a new USER
  - [x] REQ: APIs for logging in and out of an existing account
  - [x] REQ: APIs for modifying a USER
    - [x] REQ: Make sure you can't modify any user other than yourself
  - [x] REQ: APIs for deleting a USER
    - [x] REQ: Make sure you can't delete any user other than yourself
 
This should be enough for THIS task... task related to biometrics and recipes will be defined elsewhere for later.

**Comment by fcrisafulli-dev** [comment]
Old issue.
